### ISSUE TITLE
Does this plugin work with Cloudflare in front?

### ISSUE THREAD

**Issue by Allram** [juitde/traefik-plugin-fail2ban#3]
I see that this plugin takes inspiration from TomMoulard's Fail2ban plugin for Traefik.
That plugin does not currently work with Cloudflare in front as it only uses the request's IP for banning, does this plugin work with Cloudflare in front?

See more information here: https://github.com/tomMoulard/fail2ban/issues/84

**Comment by dkreuer** [comment]
Hi! Thanks for your interest.
Currently there is no way to specify a different source for the remote ip. I‘m considering extending the plugin but currently have no time to do so.
